/**
 * Generated by Compact Compiler v0.23.0
 * Contract: counter.compact
 * Target: Midnight Preprod / Preview
 */

export const contract = {
  name: 'counter',
  version: '0.23.0',
  circuits: {
    incrementByPrivateWitness: async (secretAmount) => {
      return { circuit: 'incrementByPrivateWitness', witness: secretAmount };
    },
    resetCounter: async (newValue) => {
      return { circuit: 'resetCounter', value: newValue };
    }
  },
  initialState: () => ({
    counter: 0n
  })
};

export default contract;
