/**
 * Generated by Compact Compiler v0.23.0
 * Contract: counter.compact
 * Target: Midnight Preprod / Preview
 */

export interface Contract<T = any> {
  circuits: {
    incrementByPrivateWitness(secretAmount: bigint | number): Promise<void>;
    resetCounter(newValue: bigint | number): Promise<void>;
  };
  initialState(): {
    counter: bigint;
  };
}

export interface Witnesses<T = any> {
  secretWitness(context: T): bigint | number;
}

export declare const contract: Contract;
export default contract;
